export const products = [
    { id: 1, name: 'Cuaderno Raya', price: 27, stock: 10, image: '././public/Logo.jpg' },
    { id: 2, name: 'Cuaderno Cuadro Grande', price: 27, stock: 10, image: '././public/Logo.jpg' },
    { id: 3, name: 'Cuaderno Cuadro Chico', price: 27, stock: 10, image: '././public/Logo.jpg' },
    { id: 4, name: 'Lapicero Negro', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 5, name: 'Lapicero Azul', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 6, name: 'Lapicero Rojo', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 7, name: 'Folder Carta', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 8, name: 'Folder Oficio', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 9, name: 'Lapiz', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 10, name: 'Lapiz Infinito', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 11, name: 'Colores Mapita', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 12, name: 'Colores Blanca Nieves', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 13, name: 'Colores School', price: 30, stock: 10, image: '././public/Logo.jpg' },
    { id: 14, name: 'Regla', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 15, name: 'Paquete de reglas', price: 30, stock: 10, image: '././public/Logo.jpg' },
    { id: 16, name: 'Juego Geometrico', price: 45, stock: 10, image: '././public/Logo.jpg' },
    { id: 17, name: 'Papel China', price: 2, stock: 10, image: '././public/Logo.jpg' },
    { id: 18, name: 'Papel Crepe', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 19, name: 'Papel Mural', price: 7, stock: 10, image: '././public/Logo.jpg' },
    { id: 20, name: 'Papel Cascaron Entero', price: 18, stock: 10, image: '././public/Logo.jpg' },
    { id: 21, name: 'Cartulina', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 22, name: 'Papel Iris', price: 9, stock: 10, image: '././public/Logo.jpg' },
    { id: 23, name: 'Foami', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 24, name: 'Tijeras Punta Mocha', price: 22, stock: 10, image: '././public/Logo.jpg' },
    { id: 25, name: 'Goma', price: 9, stock: 10, image: '././public/Logo.jpg' },
    { id: 26, name: 'Tijeras Punta Fina', price: 25, stock: 10, image: '././public/Logo.jpg' },
    { id: 27, name: 'Tijera de Diseño', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 28, name: 'Sacapuntas Normal', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 29, name: 'Sacapuntas de Diseño', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 30, name: 'Corrector Lapiz', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 31, name: 'Corrector Brocha', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 32, name: 'Corrector Corrido', price: 25, stock: 10, image: '././public/Logo.jpg' },
    { id: 33, name: 'Bicolor', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 34, name: 'Lupas', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 35, name: 'Cuaderno Frances Cuadro Chico', price: 22, stock: 10, image: '././public/Logo.jpg' },
    { id: 36, name: 'Cuaderno Frances Cuadro Grande', price: 22, stock: 10, image: '././public/Logo.jpg' },
    { id: 37, name: 'Cuaderno Frances Raya', price: 22, stock: 10, image: '././public/Logo.jpg' },
    { id: 38, name: 'Cuaderno Frances Doble Raya', price: 22, stock: 10, image: '././public/Logo.jpg' },
    { id: 39, name: 'Marcador de Agua', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 40, name: 'Marcador de Aceite', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 41, name: 'Marcador Permanente', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 42, name: 'Resistol Adhesivo Grande', price: 30, stock: 10, image: '././public/Logo.jpg' },
    { id: 43, name: 'Resistol Adhesivo Mediano', price: 21, stock: 10, image: '././public/Logo.jpg' },
    { id: 44, name: 'Resistol Adhesivo Chico', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 45, name: 'Pegamento Grande', price: 25, stock: 10, image: '././public/Logo.jpg' },
    { id: 46, name: 'Pegamento Mediano', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 47, name: 'Pegamento Chico', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 48, name: 'Barra de Silicon', price: 3, stock: 10, image: '././public/Logo.jpg' },
    { id: 49, name: 'Foami Normal', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 50, name: 'Foami Diamantado', price: 7, stock: 10, image: '././public/Logo.jpg' },
    { id: 51, name: 'Bola de Unicel #1', price: 1, stock: 10, image: '././public/Logo.jpg' },
    { id: 52, name: 'Bola de Unicel #2', price: 2, stock: 10, image: '././public/Logo.jpg' },
    { id: 53, name: 'Bola de Unicel #3', price: 3, stock: 10, image: '././public/Logo.jpg' },
    { id: 54, name: 'Bola de Unicel #4', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 55, name: 'Bola de Unicel #5', price: 5, stock: 10, image: '././public/Logo.jpg' },
    { id: 56, name: 'Bola de Unicel #6', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 57, name: 'Bola de Unicel #7', price: 7, stock: 10, image: '././public/Logo.jpg' },
    { id: 58, name: 'Bola de Unicel #8', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 59, name: 'Bola de Unicel #9', price: 9, stock: 10, image: '././public/Logo.jpg' },
    { id: 60, name: 'Bola de Unicel #10', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 61, name: 'Hoja de Unicel', price: 20, stock: 10, image: '././public/Logo.jpg' },
    { id: 62, name: 'Papel Cascaron 1/8', price: 14, stock: 10, image: '././public/Logo.jpg' },
    { id: 63, name: 'Papel Cascaron 1/4', price: 7, stock: 10, image: '././public/Logo.jpg' },
    { id: 64, name: 'Cinta Decorativa Grande', price: 6, stock: 10, image: ':././public/Logo.jpg' },
    { id: 65, name: 'Cinta Decorativa Chica', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 66, name: 'Cinta de Pegar Extra Chica', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 67, name: 'Cinta de Pegar Chica', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 68, name: 'Cinta de Pegar Mediana', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 69, name: 'Cinta de Pegar Grande', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 70, name: 'Cinta de Pegar Extra Grande', price: 25, stock: 10, image: '././public/Logo.jpg' },
    { id: 71, name: 'Calculadora Cientifica', price: 100, stock: 10, image: '././public/Logo.jpg' },
    { id: 72, name: 'Compas', price: 20, stock: 10, image: '././public/Logo.jpg' },
    { id: 73, name: 'Palo de Bandera Grande', price: 5, stock: 10, image: '././public/Logo.jpg' },
    { id: 74, name: 'Palo de Bandera Mediano', price: 4, stock: 10, image: '././public/Logo.jpg' },
    { id: 75, name: 'Palo de Bandera Chico', price: 3, stock: 10, image: '././public/Logo.jpg' },
    { id: 76, name: 'Diarios', price: 20, stock: 10, image: '././public/Logo.jpg' },
    { id: 77, name: 'Papel Corrugado', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 78, name: 'Pliego de Foami', price: 35, stock: 10, image: '././public/Logo.jpg' },
    { id: 79, name: 'Papel America', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 80, name: 'Cartulina', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 81, name: 'Mica Gruesa', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 82, name: 'Mica Delgada', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 83, name: 'Mica de Diseño', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 84, name: 'Masking', price: 25, stock: 10, image: '././public/Logo.jpg' },
    { id: 85, name: 'Cuaderno Chico Raya', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 86, name: 'Cuaderno Chico Doble Raya', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 87, name: 'Cuaderno Chico Cuadro Grande', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 88, name: 'Cuaderno Chico Cuadro Chico', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 89, name: 'Cuaderno de Dibujo', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 90, name: 'Cuaderno de Dibujo Profesional', price: 27, stock: 10, image: '././public/Logo.jpg' },
    { id: 91, name: 'Engargolados', price: 15, stock: 10, image: '././public/Logo.jpg' },
    { id: 92, name: 'Enmicado', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 93, name: 'Pintura Vinci', price: 12, stock: 10, image: '././public/Logo.jpg' },
    { id: 94, name: 'Pintura Acrilico', price: 10, stock: 10, image: '././public/Logo.jpg' },
    { id: 95, name: 'Hojas de Color', price: 1, stock: 10, image: '././public/Logo.jpg' },
    { id: 96, name: 'Pilas AA', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 97, name: 'Pilas AAA', price: 8, stock: 10, image: '././public/Logo.jpg' },
    { id: 98, name: 'Papel Bond Rayado', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 99, name: 'Papel Bond Blanco', price: 6, stock: 10, image: '././public/Logo.jpg' },
    { id: 100, name: 'Papel Bond Cuadriculado', price: 6, stock: 10, image: '././public/Logo.jpg' },
  ];